Repository gisce/powerprofile, pull requests merged in 2025-04, with the labels that each got.

#46 FIX fill_gaps, se añade soporte para llenar más campos de fecha
  powerprofile/powerprofile.py
Labels: bug, enhancement, patch

#47 Update workflows
  .github/workflows/python2.7-app.yml
  .github/workflows/release.yml
Labels: patch

#48 Afegim interpolació QH seguin el PO 10.5 Annex 11
  powerprofile/powerprofile.py
  powerprofile/utils.py
  spec/interpolate_spec.py
  spec/powerprofileqh_spec.py
Labels: enhancement
